### ISSUE TITLE
Permission denied on mac m1 | ARM

### ISSUE THREAD

**Issue by siddarthkay** [mAch17/cowin-rs#1]
Hi!
Great initiative btw!
Are there any dependencies required to execute this on a command line running on mac m1?

Below is screenshot when i run it after being logged in as root : 

<img width="571" alt="Screenshot 2021-05-17 at 12 35 42 PM" src="https://user-images.githubusercontent.com/64726664/118445689-66f8bd00-b70c-11eb-9aa6-a055ba9370f8.png">

**Comment by mAch17** [comment]
Hi,

That binary was compiled on Linux and not a Mac and maybe that is why its not working. I don't have a Mac with me right now so couldn't compile it for Mac OS.
If you have Rust toolchain installed on your Mac, you can run a cargo build in the directory containing cargo.toml and get a binary for Mac directly. If you can build it, please share here as well. I will put it as a Mac binary.

**Comment by mAch17** [comment]
I will see meanwhile if I can get it built on a Mac.

**Comment by siddarthkay** [comment]
Thanks for letting me know.
Yeah I got the build working after cargo build in the directory.
Unfortunately I can not attach files as a comment, I'll make a PR to your repo with the binary for macos

**Comment by mAch17** [comment]
Sure. Thanks a lot for contributing.

**Comment by siddarthkay** [comment]
I have made a new branch,
I'll however need push access to submit the PR 
my github username is on this email : siddarthkay@gmail.com

**Comment by mAch17** [comment]
I added you as a collaborator. You can create a new "0.1-rc-mac" release.
